F/7109 scaffold new HubGroup entity
Esri/hub.js pull request #1113
Opened 2023-07-12 21:32 UTC by vivzhang

1. Description:

1. Instructions for testing:

1. Closes Issues: #<number> (if appropriate)

1. [ ] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://esri.github.io/hub-components/storybook/?path=/story/guides-documentation--page)

1. [ ] used semantic commit messages
  
1. [ ] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)

1. [ ] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions for more details.

2023-07-25 13:38 UTC, dbouwman requested changes
This is a solid start - we need to review a number of the `IHubGroup` properties and how they are mapped to/from the `IGroup`.

2023-07-25 17:53 UTC, vivzhang commented on packages/common/src/core/types/IHubGroup.ts
> +  membershipAccess?: string;
According to [`this confluence`](https://confluencewikidev.esri.com/pages/viewpage.action?pageId=105316739),  "Privileged users will be able to specify who can, thus who cannot, join any group in their organization." If this prop is passed in when a group is created, the default value will be "org".

2023-07-31 15:38 UTC, dbouwman commented on packages/common/src/groups/HubGroup.ts
> +  /**
We can just remove this

2023-07-31 15:47 UTC, dbouwman approved these changes
Only one small ask - please add some permissions into the e2e - just to verify that the permissions are stored in `.properties.permissions` and then read back out. I'm like 99% sure this will be fine, but it's a good practice to verify :)

2023-07-31 17:53 UTC, merged