feat: add new IWithContent trait, extend various types to support storing content on hub project
Esri/hub.js pull request #960
Opened 2023-01-17 19:45 UTC by vivzhang

affects: @esri/hub-common

ISSUES CLOSED: 5497

1. Description:
- Add new `IWithContent` trait
- Move `IGallerySelection` from hub-components
- Extend `IHubProject` and `getPropertyMap`

1. Instructions for testing:

1. Closes Issues: #<number> (if appropriate)

1. [ ] used semantic commit messages
  
1. [ ] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)

2023-01-17 19:47 UTC, vivzhang commented on packages/common/src/search/types/types.ts
> +
Not sure if this is the best place to store it, or `common/src/core/types`?

2023-01-17 22:30 UTC, juliannemarik approved these changes
This looks good to me, but I might double check with Dave, especially on where to store that `IGallerySelection`

2023-01-17 23:00 UTC, dbouwman commented
The implementation is well done on @vivzhang... but I fear this naming + structure will be confusing down the line.

I think we should re-consider the naming (sorry I did not catch this last week @jul11252 ) - `IWithContent` is confusing because we refer to "every item that's not site/page/initiative/project" as "Content" (thus `IHubContent`), and that interface somewhat suggests this is how we'd associate searchable content with the entity, but really, we do that via the Catalog /`IWithCatalog` interface

This also seems like something specific to the "View" for an item... could we put this into `IWithViewSettings` as `.highlightItems: string[]`? I'm not sure we'll use the whole `IGallerySelection`, so if we can, let's strip out the other array props that are not needed. (If this is a big pain, we can probably skip this, but it's worth considering what would happen if the `.groups` array had values in it?)

2023-01-17 23:00 UTC, dbouwman requested changes
see my comment on the PR

2023-01-18 19:29 UTC, juliannemarik commented on packages/common/src/core/schemas/hubproject.ts
> +      labelKey: "{{i18nScope}}.relatedItems.label",
Looks like the AC calls out that the section should have helper text, so you'll want to add that to the section's `options`. Something like: 
```ts
{
  type: "Section",
  options: {
    helperText: {
      labelKey: "{{i18nScope}}.relatedItems.helperText"
    }
  },
  elements: [ ... ]
}
```

2023-01-18 19:29 UTC, juliannemarik commented on packages/common/src/core/schemas/hubproject.ts
> +        relatedItems: {
Sorry I think I might have been incorrect earlier when I said you could call this `relatedItems`. We'll actually need the property defined on the schema to match the property we're storing on the item, so we'll want to make this `relatedItemIds`

2023-01-18 19:29 UTC, juliannemarik commented on packages/common/src/core/schemas/hubproject.ts
> +          scope: "/properties/relatedItems",
since this is nested under `view`, the scope will need to be `"/properties/view/properties/relatedItemIds"`

2023-01-18 20:04 UTC, juliannemarik approved these changes

2023-01-18 20:14 UTC, merged